name: Build AmneziaWG on ImmortalWrt

on:
  workflow_dispatch:
    inputs:
      immortal_tag:
        description: "ImmortalWrt release/tag"
        required: true
        type: string
        default: "24.10.3"
      pkgarch:
        description: "Package architecture"
        required: true
        type: string
        default: "aarch64_cortex-a53"
      target:
        description: "Target platform"
        required: true
        type: string
        default: "mediatek"
      subtarget:
        description: "Target subplatform"
        required: true
        type: string
        default: "filogic"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AmneziaWG
        uses: actions/checkout@v5
        with:
          repository: kozhini/amneziawg-openwrt
          ref: master
          fetch-depth: 0
          path: amneziawg

      - name: Download & extract ImmortalWrt SDK
        run: |
          mkdir -p sdk
          wget -O sdk.tar.zst https://downloads.immortalwrt.org/releases/${{ inputs.immortal_tag }}/targets/${{ inputs.target}}/${{ inputs.subtarget}}/immortalwrt-sdk-${{ inputs.immortal_tag }}-${{ inputs.target}}-${{ inputs.subtarget}}_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf sdk.tar.zst -C sdk --strip-components=1

      - name: Copy AmneziaWG packages into SDK
        run: |
          mkdir -p sdk/package
          cp -r amneziawg/kmod-amneziawg sdk/package/
          cp -r amneziawg/luci-proto-amneziawg sdk/package/
          cp -r amneziawg/amneziawg-tools sdk/package/

      - name: Update PKG_SOURCE_VERSION & HASH
        run: |
          set -e -x
          update_pkg() {
            local pkg_dir="$1"
            local repo="$2"
            local branch="$3"
            echo "--- Updating $pkg_dir from $branch ---"
            commit=$(git ls-remote "$repo" "$branch" | awk '{print $1; exit}')
            url="$repo/archive/$commit.tar.gz"
            hash=$(curl -L --retry 3 -s "$url" | sha256sum | cut -d' ' -f1)
            if [ -d "$pkg_dir" ]; then
              cd "$pkg_dir"
              sed -i "s/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$commit/" Makefile
              sed -i "s/^PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$hash/" Makefile
              cd - >/dev/null
              echo "--- $pkg_dir updated: $commit ---"
            else
              echo "Warning: directory $pkg_dir not found"
            fi
          }
          update_pkg "kmod-amneziawg" "https://github.com/amnezia-vpn/amneziawg-linux-kernel-module.git" "feature/awg2"
          update_pkg "amneziawg-tools" "https://github.com/amnezia-vpn/amneziawg-tools.git" "master"
          # luci-proto-amneziawg не обновляется автоматически

      - name: Build AmneziaWG packages in SDK
        run: |
          cd sdk

          # Копируем готовый .config с включенными нужными пакетами
          if [ ! -f .config ]; then
            echo "--- Using default config for SDK ---"
            # config.buildinfo из ImmortalWrt уже содержит нужные пакеты
            wget -q https://downloads.immortalwrt.org/releases/24.10.3/targets/mediatek/filogic/config.buildinfo -O .config
            echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
            echo "CONFIG_PACKAGE_amneziawg-tools=m" >> .config
            echo "CONFIG_PACKAGE_luci-proto-amneziawg=m" >> .config
            make defconfig
          fi

          # Сборка пакетов (kmod, amneziawg-tools, luci-proto)
          for pkg in kmod-amneziawg amneziawg-tools luci-proto-amneziawg; do
            echo "--- Building package: $pkg ---"
            make package/$pkg/{clean,download,prepare,compile} -j$(nproc)
          done


      - name: Prepare artifacts
        run: |
          cd sdk
          mkdir -p awgrelease
          postfix="v${{ inputs.immortal_tag }}_${{ inputs.pkgarch }}_${{ inputs.target }}_${{ inputs.subtarget }}"
          cp bin/packages/${{ inputs.pkgarch }}/awgopenwrt/amneziawg-tools_*.ipk awgrelease/amneziawg-tools_${postfix}.ipk
          cp bin/packages/${{ inputs.pkgarch }}/awgopenwrt/luci-proto-amneziawg_*.ipk awgrelease/luci-proto-amneziawg_${postfix}.ipk
          cp bin/targets/${{ inputs.target}}/${{ inputs.subtarget}}/packages/kmod-amneziawg_*.ipk awgrelease/kmod-amneziawg_${postfix}.ipk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-${{ inputs.immortal_tag }}_${{ inputs.pkgarch }}_${{ inputs.target }}_${{ inputs.subtarget }}
          path: sdk/awgrelease/*
